[package]
name = "untitled"
version = "0.1.0"
authors = ["wangchao <1613529835@qq.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rltk = { version = "0.8.0" }